Import('env')

env = env.Clone()
env.Append(ENV = dict(
    PKG_CONFIG_PATH = env.Dir(
        "../libs/libserialport/install/lib/pkgconfig"
    ).abspath
))

env.PkgConfigGetCflags("libserialport")

# static linkage
env.Append(LIBS = File("../libs/libserialport/install/lib/libserialport.a"))

conf = env.Configure()

if conf.CheckDeclaration("WIN32"):
    # for libserialport
    conf.env.Append(LIBS = ["-lhid", "-lsetupapi"])

env = conf.Finish()

prog = env.Program("serial", ["main.cpp"])
