Import("env")

# Libs first because they do `Export`.
SConscript(
    exports = ["env"],
    dirs = [
        "libs",
    ]
)

SConscript(
    exports = ["env"],
    dirs = [
        "simple",
        "serial",
    ]
)
